= 01 Parse First Name
:favicon: https://fernandobasso.dev/cmdline.png
:icons: font
:sectlinks:
:sectnums!:
:toclevels: 6
:toc: left
:source-highlighter: highlight.js
:experimental:
:imagesdir: __assets



This first example is *not* meant to be a tutorial on the syntax of one particular language or the API of one particular library or framework.
The goal is to cover the basic thought process (because _thought works_ 💪) and get some initial mental model on _how to actually write code using TDD_ — and we all know it: thought works 💪 (pun intended) — when designing and implementing code.

== parseFirstName()

We are given an input which is supposed to contain a person's name.
From that input, we should parse the first name out of it.

The idea is that we create a function that takes the string which is supposed to be a person's name, and returns the first name.

[NOTE]
====
Some of these tests cases are required only because we are working with a dynamically-typed language, and would not be necessary for a statically typed language.
====

=== Two-word strings

Parse the first name out of a string that contains first and last name.

----
Ahsoka Tano    → Ahsoka
----

=== One-word strings

Parse first name out of a string that contains only a single word.

----
Yoda    → Yoda
----

=== Three-or-more-word strings

Parse first name out of a string that contains three or more words.

----
Padmé Amidala Naberrie                  → Padmé
Albus Percival Wulfric Brian Dumbledore → Albus
----

=== Delimit by dash or underscore

Now, our input does not come with space-separated words only.
Name parts may also be separated by a minus sign or underscore.

----
Ahsoka-Tano    → Ahsoka
Aayla-Secura   → Aayla
Ahsoka_Tano    → Ahsoka
Aayla_Secura   → Aayla
----

Should we use conditionals to test for space, minus sign and underscore and split based on the result of the condition?
Perhaps replace the _if then else_ condition with a _switch case_?

[source,javascript,lineos]
----
if (name.includes(' ')) {
  // Split at space.
} else if (name.includes('-')) {
  // Split at '-'.
} else if (name.includes('_')) {
  // Split at '_'.
} else {
  // None of ' ', '-', or '_'.
}
----

=== Configurable delimiter

What if we have to allow our function to provide any character (or characters) as a delimiter?
What if names are provided as tab-separated or comma-separated strings?

It is clear by now that the conditionals do not scale, and that we probably need a second parameter to specify the delimiter.

After the tests are green, maybe refactor to use regex instead?

But will we have to search through the codebase and change all the existing uses of `parseFirstName()`‽
Or we can use some technique or syntax feature of the programming language to not require changes _everywhere_?

----
Albus;Percival;Wulfric;Brian;Dumbledore → Albus
Ahsoka\tTano                            → Ahsoka
Aayla\nSecura                           → Aayla
----
