= Hands-on TDD with JavaScript
:toc: left
:source-highlighter: highlight.js
:pygments-css: class
:icons: font
:uri_group: https://gitlab.com/hands-on-tdd-with-javascript
:name_group: Hands-On TDD with JavaScript
:uri_repo_gitlab: https://gitlab.com/hands-on-tdd-with-javascript/parse-name
:uri_repo_github: https://github.com/Hands-On-TDD-With-JavaScript/parseName

This repository is part of the link:{uri_group}[{name_group}] series on practical test driven development (TDD).
We try to focus on _practical examples_ based on testing and TDD concepts and ideas.

[NOTE]
====
The link:{uri_repo_gitlab}[main repo is the one on Gitlab].
The link:{uri_repo_github}[Github repo] is only a mirror.
Discussion, issues, etc. should be happen on link:{uri_repo_gitlab}[Gitlab].
====

== Intro

This is the first example of the series.
The goal is to _parse (or extract) a person's first name_ from a given input, then later create a function that composes a greeting message with that first name.
Sounds easy, and it most likely _is_ easy.

Yet, we have found this example to be a reasonably good introduction to the topic of TDD because it brings to light a few important things:

- We use tests to help design the implementation of new requirements.
- Having passing tests allows us to refactor with confidence (an old TDD cliche but very true).
- Existing tests work as regression tests when covering new requirements and edge cases.
- Test descriptions serve as documentation and specification on the features in question.

In short, it allows the discussion of several concepts and ideas that are useful for any other, more complex situation to come when doing TDD.

Through this example we can see how TDD offer at least these benefits:

* It helps us design and better understand a solution for a problem;
* It helps us identify and tackle edge cases;
* It helps us think about and document footnote:[Tests are documentation too!] the set of inputs our functions (or methods) accept (the domain of a function);
* It enables us to move forward adding more features with free regression tests to assure new code does not break things that are already working fine;
* It encourages refactoring because it relives developers from the burden of manually testing that everything still works fine after code changes;

== Exercises

- link:./01-parse-first-name.adoc[Parse first name^].
- link:./02-greeting.adoc[Greeting^].

== Licensing Information

See link:LICENSE.txt[LICENSE.txt].

