= parseName - Hands-on TDD with JavaScript
:toc: left
:source-highlighter: pygments
:pygments-css: class
:icons: font
:uri_group: https://gitlab.com/hands-on-tdd-with-javascript
:name_group: Hands-On TDD with JavaScript
:uri_repo_gitlab: https://gitlab.com/hands-on-tdd-with-javascript/parsename
:uri_repo_github: https://github.com/Hands-On-TDD-With-JavaScript/parseName

This repository is part of the link:{uri_group}[{name_group}].
A hands-on series on practical Test Driven Development examples, concepts and motivation.

[NOTE]
====
The link:{uri_repo_gitlab}[main repo is the one on Gitlab].
The link:{uri_repo_github}[Github repo] is only a mirror.
Discussion, issues, etc. should be happen on link:{uri_repo_gitlab}[Gitlab].
====

[NOTE]
====
Github doesn't do nice rendering of Asciidoctor (`.adoc`) files.
Gitlab does a much better job at this.
You are advised to read this text on link:{uri_repo_gitlab}[Gitlab].
====

== Intro

This is the first example of the series.
The goal is to _parse a persons first name_.
Sounds easy, and it most likely _is_ easy.
Yet, I have found this example to be a very good introduction to the topic of Test Driven Development.

It allows the discussion of several concepts and ideas that are useful for any other, more complex situation to come when doing TDD.

Through this example we can see how TDD helps us with the following:

* Helping us design and better understand a solution for a problem;

* Tackle edge cases;

* Document the range of inputs our functions (or methods) cover (the domain of a function);

* It enables us to move forward adding more features with free regression tests to assure new code does not break things that are already working fine.

* It encourages refactoring because it relives developers from the burden of manually testing everything still works fine after code changes.

== parseFirstName

We are given an input which is supposed to contain a person's name.
From that input, we should parse the first name out of it.

The idea is that we create a function that takes the name string, and returns the first name.

[NOTE]
====
Some of these tests cases are required only because we are working with a dynamically-typed language, and would not be necessary for a statically typed language.
====

=== two-word strings

Parse the first name out of a string that contains first and last name.
Example inputs to outputs:

----
Ahsoka Tano    → Ahsoka
Obi-Wan Kenobi → Obi-Wan
----

Note that “Obi-Wan” is

=== one-word strings

Parse first name out of a string that contains only a single word.
Example inputs to outputs:

----
Yoda    → Yoda
Obi-Wan → Obi-Wan
----

=== three-or-more-word strings

Parse first name out of a string that contains three or more words.
Example inputs to outputs:

----
Padmé Amidala Naberrie                  → Padmé
Albus Percival Wulfric Brian Dumbledore → Albus
----

=== delimit by dash or underscore

Now, our input does not come with space-saparated words only. Name parts may also be separated by a minus sign or underscore.

----
Ahsoka-Tano    → Ahsoka
Aayla Secura   → Aayla
Obi-Wan Kenobi → Obi
----

Should we conditionals to test for space, minus sign and underscore and split based on the result of the condition?

[source,javascript,lineos]
----
if (name.includes(' ')) {
  // Split at space.
} else if (name.includes('-')) {
  // Split at '-'.
} else if (name.includes('_')) {
  // Split at '_'.
} else {
  // None of ' ', '-', or '_'.
}
----

=== configurable delimiter

What if we have to allow our function to provide any character (or characters) as a delimiter? What if names come in a tab-separated or comma-separated.

It is clear by now that the conditionals do not scale, and that we probably need a second parameter to specify the delimiter.
But will we have to search through the code base and change all the existing uses of `parseFirstName`‽

----
Albus;Percival;Wulfric;Brian;Dumbledore → Albus
Ahsoka\tTano                            → Ahsoka
Aayla\nSecura                           → Aayla
----

== Licensing Information

See link:LICENSE.txt[LICENSE.txt].

